apiVersion: v1
kind: Service
metadata:
  name: k6-exporter
  namespace: monitoring
  labels:
    app: k6-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: k6-exporter